# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgresdb
    ports:
      - "54320:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 3s
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgresdb
    volumes:
      - ./api:/app
    command: >
      /bin/sh -c "pip install --no-cache-dir -r /app/requirements.txt &&
                  uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  pgdata: